version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data
  reponano:
    container_name: "fullstack-challenge"
    image: "reponano:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - fastapi-nano
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: "bitnami/elasticsearch:latest"
    environment:
      - network.bind_host=database
      - network.publish_host=0.0.0.0
      - network.host=0.0.0.0

  indexer:
    build: indexer/
    depends_on:
      - reponano
    container_name: indexer

volumes:
  node-red-data:

networks:
  node-red-net: